# Generated by Django 4.2.11 on 2024-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
