# Generated by Django 4.2.11 on 2024-04-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_appliedjobs_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='recruiter',
        ),
    ]
