# Generated by Django 4.2.11 on 2024-04-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_appliedjobs_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='employer',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
