# Generated by Django 4.2.11 on 2024-04-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_appliedjobs_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='marksheet',
            field=models.FileField(upload_to='media/'),
        ),
    ]
