# Generated by Django 4.2.11 on 2024-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_employer_image_alter_viauser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='viauser',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
